### ISSUE TITLE
mv -force

### ISSUE THREAD

**Issue by sudosun** [netzfisch/rpi-vpn-server#2]
docker exec vpnserver setup user vpnuser password

```
mv: unrecognized option: force
BusyBox v1.23.2 (2015-04-25 06:52:59 GMT) multi-call binary.

Usage: mv [-fin] SOURCE DEST
or: mv [-fin] SOURCE... DIRECTORY

Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY

    -f  Don't prompt before overwriting
    -i  Interactive, prompt before overwrite
    -n  Don't overwrite an existing file

Stopping strongSwan IPsec...
```

i use
Linux black-pearl 4.4.15-hypriotos+ #2 PREEMPT Mon Jul 25 09:18:11 UTC 2016 armv6l GNU/Linux

**Comment by netzfisch** [comment]
It looks like the mounted directory is not available!
Did you start the docker container "vpnserver" with the option "--volume /secrets:/mnt"?

If above guess does not help, go into the running container and verify manually by `$ docker exec -it vpnserver ash`, see allso [debugging section](https://github.com/netzfisch/rpi-vpn-server#debugging) in the README!
